name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Test compiler
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/app-yaml-env-compiler@v1
